import type { NextPage } from 'next';
import Head from 'next/head';
import { Layout } from '../components/templates/layout/Layout';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}></main>
    </Layout>
  );
};

export default Home;
